spring:
  application:
    name: streamline
    
  datasource:
    url: jdbc:postgresql://localhost:5432/streamline
    username: ${SPRING_DATASOURCE_USERNAME:app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:app_pass}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      data-locations:
      - classpath:db/data/*.sql

server:
  port: 8080

logging:
  level:
    root: INFO
    "[com.munichre]": DEBUG
