spring:
  application:
    name: streamline
    
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/streamline}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      data-locations:
      - classpath:db/data/*.sql

server:
  port: 8080

google:
    application:
      credentials: ${GOOGLE_APPLICATION_CREDENTIALS:src/main/resources/serviceAccountKey.json}    

firebase:
  project-id: ${FIREBASE_PROJECT_ID:streamline-488500}

logging:
  level:
    root: INFO
    "[com.munichre]": DEBUG
