spring:
  application:
    name: streamline

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS:src/main/resources/serviceAccountKey.json}

firebase:
  project-id: ${FIREBASE_PROJECT_ID:streamline-488500}

logging:
  level:
    root: INFO
    "[com.munichre]": DEBUG